package Exceptions;

public class E5 {
    //try catch finally block
	public static void main(String[] args) {
		// TODO Auto-generated method stub
     try {
		System.out.println(67);
	} catch (Exception ref) {
		// TODO: handle exception
		System.out.println("Exception Handled");
	}
     finally {
		System.out.println("Thank You So Much");
	}
  }

}
